arb-dir: lib/core/config/l10n
template-arb-file: app_es.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/config/l10n/generated
synthetic-package: false
output-class: AppLocalizations