name: kara
description: "Practice project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: 1.19.1
  device_info_plus: ^10.1.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.0.0
  shared_preferences: ^2.2.3
  yaml: ^3.1.2
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  melos: ^6.0.0
  mockito: ^5.4.4
  retrofit_generator: ^8.1.0
  riverpod_test: ^0.1.4
  test: any
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icons/kara_launcher.png"
  adaptive_icon_background: "0xFF420296"
  ios: true
  android: true